### ISSUE TITLE
how do you get grafana.db in the first place

### ISSUE THREAD

**Issue by huahuayu** [hadv/fantom-prometheus#1]
Hi, from the compose file you mapping the host file and container file
https://github.com/hadv/fantom-prometheus/blob/18e43fb5ee4447a55a238852e49b9ad8eb3e6691/docker-compose.yml#L27

But how do you get `grafana.db` (and the init content inside it) in the first place?

**Comment by hadv** [comment]
Ah, I get it from a geth prometheus repo and use it for an opera node. Then we can login into the Grafana dashboard to update smth we want, all the changes be recorded into the `grafana.db` then we can use it afterward for opera

**Comment by huahuayu** [comment]
I see, thanks!
